 //: Try out different buffers
\sapporo.set(\buf, \melodic_road.bufnum);
\sapporo.set(\buf, \sweet_crickets.bufnum);
\sapporo.set(\buf, \cricket_ff.bufnum);
\sapporo.set(\buf, \crickets.bufnum);
\sapporo.set(\buf, \bird_crickets.bufnum);
\sapporo.set(\buf, \cricket_taps.bufnum);
\sapporo.set(\buf, \crossing.bufnum);
\sapporo.set(\buf, \echo_crickets.bufnum);
\sapporo.set(\buf, \hanbaiki.bufnum);
\sapporo.set(\buf, \lake_plane.bufnum);
\sapporo.set(\buf, \loud_crickets.bufnum);
\sapporo.set(\buf, \rough_steps.bufnum)

//:
\corfu.set(\buf, \melodic_road.bufnum);
\corfu.set(\buf, \sweet_crickets.bufnum);
\corfu.set(\buf, \cricket_ff.bufnum);
\corfu.set(\buf, \crickets.bufnum);
\corfu.set(\buf, \bird_crickets.bufnum);
\corfu.set(\buf, \cricket_taps.bufnum);
\corfu.set(\buf, \crossing.bufnum);
\corfu.set(\buf, \echo_crickets.bufnum);
\corfu.set(\buf, \hanbaiki.bufnum);
\corfu.set(\buf, \lake_plane.bufnum);
\corfu.set(\buf, \loud_crickets.bufnum);
\corfu.set(\buf, \rough_steps.bufnum)
